---
  apiVersion: v1
  kind: Secret
  metadata:
    name: awx-test-postgres-configuration
    namespace: awx
  stringData:
    host: HOST
    port: PORT
    database: DB_NAME
    username: DB_USER
    password: DB_USER_PW
    sslmode: SSL_MODE
    type: TYPE
  type: Opaque
